#! /bin/sh
### BEGIN INIT INFO
# Provides:          FastCGI servers for Django
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: Start FastCGI servers with Django.
# Description:       Django, in order to operate with FastCGI, must be started
#                    in a very specific way with manage.py. This must be done
#                    for each DJango web server that has to run.
### END INIT INFO
#
# Author:  Guillermo Fernandez Castellanos
#          <guillermo.fernandez.castellanos AT gmail.com>.
#
# Version: @(#)fastcgi 0.1 11-Jan-2007 guillermo.fernandez.castellanos AT gmail.com
#

#### SERVER SPECIFIC CONFIGURATION
DJANGO_SITES="p2p"
SITES_PATH=/sites
RUNFILES_PATH=$SITES_PATH/run
RUN_AS='p2p'
ARGS="test"
#### DO NOT CHANGE ANYTHING AFTER THIS LINE!

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="FastCGI servers"
NAME=$0
SCRIPTNAME=/etc/init.d/$NAME

#
#       Function that starts the daemon/service.
#
d_start()
{
    # Starting all Django FastCGI processes
    for SITE in $DJANGO_SITES
    do
        PID_FILE="${SITES_PATH}/${SITE}/run/django.pid"
        echo -n ", $SITE"
        if [ -f "$PID_FILE" ]; then
            echo -n " already running"
        else
            start-stop-daemon --start  \
                       --pidfile "${PID_FILE}" \
                       --chuid $RUN_AS \
                       --exec ${SITES_PATH}/${SITE}/bin/start_fastcgi.sh -- $ARGS
            echo "Started: ${PID_FILE}" 
            chmod 400 "$PID_FILE"
        fi
    done
}

#
#       Function that stops the daemon/service.
#
d_stop() {
    # Killing all Django FastCGI processes running
    for SITE in $DJANGO_SITES
    do
        PID_FILE="${SITES_PATH}/${SITE}/run/django.pid"
        echo -n ", $SITE"
        start-stop-daemon --stop --quiet --pidfile "$PID_FILE" \
                          || echo -n " not running"
        if [ -f "$PID_FILE" ]; then
           rm "$PID_FILE"
        fi
    done
}

ACTION="$1"
case "$ACTION" in
    start)
        echo -n "Starting $DESC: $NAME"
        d_start
        echo "."
        ;;

    stop)
        echo -n "Stopping $DESC: $NAME"
        d_stop
        echo "."
        ;;

    restart|force-reload)
        echo -n "Restarting $DESC: $NAME"
        d_stop
        sleep 1
        d_start
        echo "."
        ;;

    *)
        echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

exit 0
